### ISSUE TITLE
h2 i.p.v. h1

### ISSUE THREAD

**Issue by tom-2810** [Anna-Kyra/your-tribe-profile-card#1]
Je document heeft al een h1, namelijk "Wat wil je weten?". Daarom zou je de andere onderdelen verdelen als heading 2 elementen <h2>

https://github.com/Anna-Kyra/your-tribe-profile-card/blob/e17dcd5e63d46a6988e0522a511d190821a6668f/index.html#L27-L29

**Comment by Anna-Kyra** [comment]
De kopjes zijn nu heading 2
